export enum WarningType {
    SHIFT_REQUIREMENT_MISSING = 'SHIFT_REQUIREMENT_MISSING',
    EMERGENCY_SHIFT_MISSING = 'EMERGENCY_SHIFT_MISSING',
    USER_MISSING_ASSIGNMENT = 'USER_MISSING_ASSIGNMENT'
}